# Generated by Django 6.0.1 on 2026-02-03 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4, unique=True, verbose_name='currency')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rate')),
            ],
        ),
        migrations.CreateModel(
            name='OperationTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True, verbose_name='tag')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('svg', models.TextField(blank=True, default='', max_length=100, verbose_name='svg')),
            ],
            options={
                'verbose_name': 'Operation Tag',
                'verbose_name_plural': 'Operation Tags',
                'ordering': ['-tag'],
            },
        ),
        migrations.CreateModel(
            name='UserLogSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField(blank=True, default='', max_length=100, verbose_name='svg')),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('action_color', models.CharField(blank=True, default='', max_length=50, verbose_name='action_color')),
            ],
            options={
                'verbose_name': 'Log SVG',
                'verbose_name_plural': 'Logs SVGs',
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp_files/', verbose_name='file')),
                ('file_name', models.CharField(max_length=100, verbose_name='file_name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data File',
                'verbose_name_plural': 'Data Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInOutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='operation date')),
                ('title', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_link', to='users.datafile', verbose_name='file')),
                ('tag', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='users.operationtags', verbose_name='tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User In-Out',
                'verbose_name_plural': 'Users In-Out',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.CharField(blank=True, default='', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('action_svg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_svg', to='users.userlogsvg')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_currency', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.currency')),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['user', 'file_name'], name='users_dataf_user_id_ace07d_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['file', 'file_name'], name='users_dataf_file_021e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='userinoutinfo',
            index=models.Index(fields=['user', 'date'], name='users_useri_user_id_5dce7f_idx'),
        ),
        migrations.AddIndex(
            model_name='userinoutinfo',
            index=models.Index(fields=['user', 'tag'], name='users_useri_user_id_35306f_idx'),
        ),
        migrations.AddIndex(
            model_name='userinoutinfo',
            index=models.Index(fields=['user', 'file'], name='users_useri_user_id_4f61e4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractionlog',
            index=models.Index(fields=['user', 'created_at'], name='users_usera_user_id_835fca_idx'),
        ),
    ]
