# Generated by Django 6.0b1 on 2025-11-16 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True, verbose_name='tag')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('svg', models.TextField(blank=True, default='', max_length=100, verbose_name='svg')),
            ],
            options={
                'verbose_name': 'Operation Tag',
                'verbose_name_plural': 'Operation Tags',
                'ordering': ['-tag'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='temp_files', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInOutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='operation date')),
                ('title', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.datafile')),
                ('tag', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='users.operationtags', verbose_name='tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User In-Out',
                'verbose_name_plural': 'Users In-Out',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='users_useri_user_id_5dce7f_idx'), models.Index(fields=['user', 'tag'], name='users_useri_user_id_35306f_idx')],
            },
        ),
    ]
