# Generated by Django 6.0.1 on 2026-02-23 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinoutinfo',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
    ]
