# Generated by Django 6.0b1 on 2025-11-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinoutinfo',
            name='file',
        ),
    ]
