# Generated by Django 5.2.7 on 2025-10-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userinoutinfo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinoutinfo',
            name='tag',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.operationtags'),
        ),
    ]
