# Generated by Django 6.0.1 on 2026-03-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinoutinfo_title_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operationtags',
            index=models.Index(fields=['tag'], name='users_opera_tag_87c168_idx'),
        ),
    ]
