# Generated by Django 5.2.7 on 2025-10-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinoutinfo_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinoutinfo',
            old_name='ammount',
            new_name='amount',
        ),
    ]
