# Generated by Django 6.0b1 on 2025-11-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinoutinfo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='file_name'),
        ),
    ]
