# Generated by Django 6.0.1 on 2026-03-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_operationtags_users_opera_tag_87c168_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userinoutinfo',
            name='users_useri_user_id_5dce7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinoutinfo',
            name='users_useri_user_id_35306f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinoutinfo',
            name='users_useri_user_id_4f61e4_idx',
        ),
        migrations.RenameIndex(
            model_name='userinoutinfo',
            new_name='Users_Opera_title_909aea_idx',
            old_name='title_idx',
        ),
        migrations.AlterModelTable(
            name='userinoutinfo',
            table='Users_Operations',
        ),
    ]
