# Generated by Django 6.0b1 on 2025-11-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_datafile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file_name',
            field=models.CharField(max_length=100, verbose_name='file_name'),
        ),
    ]
