# Generated by Django 5.2.7 on 2025-10-12 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userinoutinfo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinoutinfo',
            name='tag',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.operationtags', verbose_name='tag'),
        ),
    ]
