# Generated by Django 6.0b1 on 2025-11-16 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_datafile_file_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Data File', 'verbose_name_plural': 'Data Files'},
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['user', 'file_name'], name='users_dataf_user_id_ace07d_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['file', 'file_name'], name='users_dataf_file_021e4e_idx'),
        ),
    ]
