# Generated by Django 6.0b1 on 2025-11-16 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_datafile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinoutinfo',
            index=models.Index(fields=['user', 'file'], name='users_useri_user_id_4f61e4_idx'),
        ),
    ]
