# Generated by Django 5.2.7 on 2025-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_operationtags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtags',
            name='svg',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='svg'),
        ),
    ]
