# Generated by Django 5.2.7 on 2025-10-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_operationtags_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtags',
            name='svg',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='svg'),
        ),
    ]
