# Generated by Django 6.0b1 on 2025-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinoutinfo_users_useri_user_id_4f61e4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to='temp_files/', verbose_name='file'),
        ),
    ]
