# Generated by Django 6.0b1 on 2025-11-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_datafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinoutinfo',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_link', to='users.datafile', verbose_name='file'),
        ),
    ]
