# Generated by Django 5.2.7 on 2025-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_operationtags_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinoutinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
