# Generated by Django 5.2.7 on 2025-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userinoutinfo_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtags',
            options={'ordering': ['-tag'], 'verbose_name': 'Operation Tag', 'verbose_name_plural': 'Operation Tags'},
        ),
        migrations.AlterField(
            model_name='operationtags',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='userinoutinfo',
            name='date',
            field=models.DateField(verbose_name='operation date'),
        ),
    ]
