# Generated by Django 5.2.8 on 2025-12-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useractionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractionlog',
            name='device_type',
        ),
    ]
