# Generated by Django 5.2.7 on 2025-10-18 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_operationtags_options_alter_operationtags_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinoutinfo',
            index=models.Index(fields=['user', 'date'], name='users_useri_user_id_5dce7f_idx'),
        ),
        migrations.AddIndex(
            model_name='userinoutinfo',
            index=models.Index(fields=['user', 'tag'], name='users_useri_user_id_35306f_idx'),
        ),
    ]
