# Generated by Django 5.2.8 on 2025-12-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_useractionlog_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='details',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
