# Generated by Django 5.2.7 on 2025-10-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userinoutinfo_users_useri_user_id_5dce7f_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userinoutinfo',
            new_name='users_useri_user_a0a52e_idx',
            old_name='users_useri_user_id_5dce7f_idx',
        ),
        migrations.RenameIndex(
            model_name='userinoutinfo',
            new_name='users_useri_user_9879aa_idx',
            old_name='users_useri_user_id_35306f_idx',
        ),
        migrations.AlterField(
            model_name='userinoutinfo',
            name='user',
            field=models.IntegerField(),
        ),
    ]
