# Generated by Django 5.2.7 on 2025-10-21 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_users_useri_user_id_5dce7f_idx_users_useri_user_a0a52e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userinoutinfo',
            new_name='users_useri_user_id_5dce7f_idx',
            old_name='users_useri_user_a0a52e_idx',
        ),
        migrations.RenameIndex(
            model_name='userinoutinfo',
            new_name='users_useri_user_id_35306f_idx',
            old_name='users_useri_user_9879aa_idx',
        ),
        migrations.AlterField(
            model_name='userinoutinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
