# Generated by Django 5.2.8 on 2025-12-30 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_useractionlog_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='users_usera_user_id_741064_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='details_gin_idx',
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='ip_address',
        ),
        migrations.AddIndex(
            model_name='useractionlog',
            index=models.Index(fields=['user', 'created_at'], name='users_usera_user_id_835fca_idx'),
        ),
    ]
