# Generated by Django 5.2.8 on 2025-12-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_useractionlog_users_usera_user_id_741064_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField(blank=True, default='', max_length=100, verbose_name='svg')),
                ('action_type', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Log SVG',
                'verbose_name_plural': 'Logs SVGs',
            },
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='action_svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_svg', to='users.userlogsvg'),
        ),
    ]
