# Generated by Django 5.2.8 on 2025-12-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userlogsvg_useractionlog_action_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogsvg',
            name='action_color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='action_color'),
        ),
    ]
