# Generated by Django 5.2.8 on 2026-01-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userlogsvg_action_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinoutinfo',
            name='updated_at',
        ),
    ]
