# Generated by Django 6.0.3 on 2026-03-29 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Mortgage', 'Mortgage'), ('Loan', 'Loan'), ('Other', 'Other'), ('Installment', 'Installment')], max_length=50)),
                ('loan_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#ffffff', max_length=50, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True)),
                ('loan_term', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('loan_insurance', models.DateField(default=None)),
                ('loan_end', models.DateField(default=None)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='was_added')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='was_modified')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loansvg', verbose_name='icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Loan',
                'ordering': ['-created_at', '-edited_at', 'user'],
            },
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='payment for 29-03-2026', max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.mainloan')),
            ],
            options={
                'db_table': 'Loan_Detail',
            },
        ),
        migrations.AddIndex(
            model_name='mainloan',
            index=models.Index(fields=['loan_type', 'loan_name'], name='Loan_loan_ty_1599b6_idx'),
        ),
        migrations.AddIndex(
            model_name='mainloan',
            index=models.Index(fields=['comment', 'loan_name'], name='Loan_comment_833d35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mainloan',
            unique_together={('loan_name', 'user')},
        ),
    ]
