# Generated by Django 6.0.3 on 2026-03-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loansvg',
            table='Loan_SVG',
        ),
    ]
