# Generated by Django 6.0.3 on 2026-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loansvg_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='title',
            field=models.CharField(default='payment for 30-03-2026', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainloan',
            name='loan_term',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
