# Generated by Django 6.0.3 on 2026-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loandetail_title_alter_mainloan_loan_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainloan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainloan',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
